### ISSUE TITLE
OCaml build flags are missing on my computer

### ISSUE THREAD

**Issue by marmistrz** [nbros/OcaIDE#23]
I enter my OCaml project's properties. There are multiple entries, such as Resource, Builders, Makefile, but the OCaml build flags entry is missing. I'm using a Makefile with a OCamlMakefile, Eclipse 3.8.1 and OcaIDE 1.2.21

**Comment by nbros** [comment]
Hello,

Since you are using a Makefile, you need to put the build flags in your Makefile. There is no property page for editing those flags.
