### ISSUE TITLE
Reading an integer from standard input in toplevel

### ISSUE THREAD

**Issue by romildo** [nbros/OcaIDE#25]
I cannot read an integer using the `read_int` function from the `Ocaml Toplevel` view. Entering the expression `read_int ()` and then entering an integer raises the exception `Failure "int_of_string"`:

```
# read_int ();;
34;;
Exception: Failure "int_of_string".
# 
```

So how can an integer be read from the `Ocaml Toplevel` view?

**Comment by nbros** [comment]
You can use Ctrl+Enter so that the Ocaml Toplevel view won't add ";;" at the end of your input.
